version: '3'

services:
  automation-metronic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automation-metronic-laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    # environment:
    #   - APP_ENV=production
    #   - APP_KEY=your_app_key  # Replace with your actual Laravel app key
    ports:
       - 9000:8000
       - 9005:9000
    networks:
      - app-network
    
      

#Docker Networks
networks:
  app-network:
    driver: bridge
    external: true
#Volumes
volumes:
  dbdata:
    driver: local